### ISSUE TITLE
When paradoxNavigationDepth = 3, right sidebar order is wrong

### ISSUE THREAD

**Issue by umbreak** [jonas/paradox-material-theme#15]
When setting in the `build.sbt`

```scala
paradoxNavigationDepth in Compile := 3
```

The right side menu items with depth 3 do not show in order (they show all of them after the menu items with depth 2).

[Here](https://bluebrain.github.io/nexus/docs/api/kg/kg-resolvers-api.html) you can find an example:

`InProject resolver` on the right hand side menu should go after `Resolver types` but it doesn't.

This does not happen with the default paradox theme.

**Comment by jonas** [comment]
Confirmed that this is a bug. There's some JavaScript code involved which restructures the navigation links: https://github.com/jonas/paradox-material-theme/blob/master/theme/src/main/assets/assets/javascripts/paradox-material-theme.js#L100

**Comment by jonas** [comment]
The fix has been released in version 0.5.1 which is on its way to Maven.
