### ISSUE TITLE
The line height for enumerations is too big

### ISSUE THREAD

**Issue by jvican** [jonas/paradox-material-theme#5]
A suggestion: I think the way enumerations are rendered in the template could be improved by reducing the line height (set by `md-typeset`). I think "crammed" enumerations can ease readability, a la http://cr.openjdk.java.net/~jrose/values/shady-values.html.

**Comment by jonas** [comment]
I tried to look for recommendations in the guidelines but could only find examples of how the guidelines themselves are styled which look pretty similar to the current styling where enumerations have the same line height as paragraphs, e.g. https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android

It's possible to add a custom stylesheet to tweak the theme else I suggest to raise the issue upstream in https://github.com/squidfunk/mkdocs-material.

**Comment by jonas** [comment]
Closing this. Please use a custom stylesheet.
