### ISSUE TITLE
404 on `search_index.json`

### ISSUE THREAD

**Issue by metasim** [jonas/paradox-material-theme#7]
I'm trying out the material theme for the first time and the search isn't working. I noted in the browser console this error when accessing the page via `sbt previewSite`:

`GET http://localhost:4000//mkdocs/search_index.json 404 (Not Found)`

The file *does* exist in `target/site/mkdocs/search_index.json`. I think the bug is in the double slash after the port number.

**Comment by jonas** [comment]
I think it is a bug in previewSite. The theme fetches the search index using an absolute URL.

**Comment by metasim** [comment]
You're right it does appear to be something with `previewSite`. I served up the pages with Python's `SimpleHTTPServer` and the search worked (beautifully!). However, I do note that the use of an absolute URL for the index is different from the other resources:

```
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /assets/stylesheets/application-0741cbeb94.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /lib/material__tabs/dist/mdc.tabs.min.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /lib/modernizr/modernizr.min.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /lib/prettify/prettify.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /assets/stylesheets/paradox-material-theme.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /assets/javascripts/application-268d62d82d.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /assets/javascripts/paradox-material-theme.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /lib/prettify/prettify.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /lib/prettify/lang-scala.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:22] "GET /assets/images/RasterFramesLogo.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:23] "GET /assets/images/RasterFrames_32x32.ico HTTP/1.1" 200 -
127.0.0.1 - - [02/Nov/2017 09:19:25] "GET //mkdocs/search_index.json HTTP/1.1" 200 -
```

Any reason why the index fetch has to be absolute? Does that restrict how the pages are deployed?

**Comment by joprice** [comment]
I'm still seeing this issue. SimpleServer works, but maybe only because it handles the double forward slashes.

**Comment by joprice** [comment]
`return e.docs.map(function(e){return e.location=t.url.base+"/"+e.location,e})})}))`

**Comment by joprice** [comment]
<img width="782" alt="screen shot 2019-02-06 at 12 48 15 am" src="https://user-images.githubusercontent.com/2175555/52322898-f305d100-29a8-11e9-95d6-14e01ac2ae7d.png">

**Comment by joprice** [comment]
To clarify, I'm seeing this when I click on a search result, not when requesting the search index file itself.

**Comment by joprice** [comment]
Reverting to 0.4.0 fixes this.

**Comment by jonas** [comment]
It might be that the behaviour changed between mkdocs-material version 2.2.2 and 3.0.3 and I forgot to adapt the integration.
