### ISSUE TITLE
Custom logo and favicon not appearing

### ISSUE THREAD

**Issue by metasim** [jonas/paradox-material-theme#8]
This may be user error, but I'm not able to get my custom logo and favicon to show up. 
I have the files saved to `src/main/paradox/assets/images` and  they show up in `target/site/assets/images`. I'm using the following configuration, but the customized values aren't apparing:

```scala
paradoxMaterialTheme in Paradox ~= {
    _.withFavicon("assets/images/RasterFrames_32x32.ico")
      .withLogo("assets/images/RasterFramesLogo.png")
}
```

When I look at the generated HTML, the header line looks like this:

```html
<link rel="shortcut icon" href="assets/images/favicon.png">
```

**Comment by metasim** [comment]
Here's the logo rendering:

<img width="222" alt="screen shot 2017-10-28 at 4 24 25 pm" src="https://user-images.githubusercontent.com/131013/32138200-8bd876ce-bbfc-11e7-88f4-ce51c8379ecf.png">

**Comment by jonas** [comment]
I added a test in 74bfae3 and was not able to reproduce this issue.

Did you also add the following to your `build.sbt`?

```sbt
ParadoxMaterialThemePlugin.paradoxMaterialThemeSettings(Paradox)
```

**Comment by metasim** [comment]
Need to check the ordering of settings. I had that in an AutoPlugin after my settings.

**Comment by metasim** [comment]
Just an FYI in case this comes up again. I'm using an `AutoPlugin` to configure my documentation settings. 

Previously I had:

```scala
override def projectSettings = Seq(
  // my plugin settings
) ++ ParadoxMaterialThemePlugin.paradoxMaterialThemeSettings(Paradox)
```

and it didn't work. But changing it to 

```scala
override def projectSettings = ParadoxMaterialThemePlugin.paradoxMaterialThemeSettings(Paradox) ++ Seq(
  // my plugin settings
)
```

it does work.
